name: OpenWrt Config

on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: main

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf config
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL git.io/depends-ubuntu-2004)
          sudo -E apt-get -qq install dos2unix
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get clean
          sudo timedatectl set-timezone Asia/Shanghai
          df -h
          
      - name: Clone source code
        run: |
          git clone https://github.com/coolsnowwolf/lede
          
      - name: Update feeds
        run: |
          cd lede
          echo 'src-git helloworld https://github.com/fw876/helloworld' >>feeds.conf.default
          echo 'src-git nas https://github.com/linkease/nas-packages.git;master' >>feeds.conf.default
          echo 'src-git nas_luci https://github.com/linkease/nas-packages-luci.git;main' >>feeds.conf.default
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Generate configuration file
        run: |
          cd lede
          rm -f ./.config*   
          make defconfig
        
      - name: Prepare artifact
        run: |
          mkdir config
          mv ./lede/.config ./config/config
          rm -rf lede
          cd config
          cp config config.txt
          unix2dos -ascii config.txt
          mv config.txt `date "+%Y-%m-%d-%H_%M_%S"`.txt
          
      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          name: config
          path: ./config/
     
      - name: Commit changes
        run: |
          git config --global user.email "304055589@qq.com"
          git config --global user.name "bluskai"
          git add .
          git commit -m "默认配置文件" -a
        
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Delete workflow runs
        uses: GitRML/delete-workflow-runs@main
        with:
          retain_days: 1
          keep_minimum_runs: 1
